---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-ent-pr-binding
spec:
  params:
    - name: target-repository
      value: $(event.pull_request.base.repo.clone_url)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: target-commit-id
      value: $(event.pull_request.base.sha)      
    - name: pr-commit-id
      value: $(event.pull_request.head.sha)
    - name: pr-commit-timestamp
      value: $(event.pull_request.head.repo.pushed_at)
    - name: pr-repository
      value: $(event.pull_request.head.repo.clone_url)
    - name: pr-branch
      value: $(event.pull_request.head.ref)
    - name: pr-number
      value: $(event.pull_request.number) 
    - name: pr-name
      value: $(event.pull_request.user.login)             
    - name: scm-type
      value: "github-ent"
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: target-repository
      value: $(event.pull_request.base.repo.clone_url)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: target-commit-id
      value: $(event.pull_request.base.sha)      
    - name: pr-commit-id
      value: $(event.pull_request.head.sha)
    - name: pr-commit-timestamp
      value: $(event.pull_request.head.repo.pushed_at)
    - name: pr-repository
      value: $(event.pull_request.head.repo.clone_url)
    - name: pr-branch
      value: $(event.pull_request.head.ref)
    - name: pr-number
      value: $(event.pull_request.number)  
    - name: pr-name
      value: $(event.pull_request.user.login)             
    - name: scm-type
      value: "github"          
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-pr-binding
spec:
  params:
    - name: target-repository
      value: "$(event.object_attributes.target.git_http_url)"
    - name: target-branch
      value: "$(event.object_attributes.target_branch)"
    - name: target-commit-id
      value: $(event.merge_request.base.sha)      
    - name: pr-repository
      value: "$(event.object_attributes.source.git_http_url)"
    - name: pr-branch
      value: "$(event.object_attributes.source_branch)"
    - name: pr-commit-id
      value: "$(event.object_attributes.last_commit.id)"
    - name: pr-commit-timestamp
      value: $(event.object_attributes.last_commit.timestamp)
    - name: pr-number
      value: $(event.object_attributes.iid) 
    - name: pr-name
      value: $(event.user.username)             
    - name: project-id
      value: $(event.project.id)
    - name: scm-type
      value: "gitlab"
